---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - hypervisor.hyperfleet.io
  resources:
  - hypervisorclusters
  - hypervisormachinetemplates
  - machineclaims
  - runnerpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hypervisor.hyperfleet.io
  resources:
  - hypervisorclusters/finalizers
  - hypervisormachinetemplates/finalizers
  - machineclaims/finalizers
  - runnerpools/finalizers
  verbs:
  - update
- apiGroups:
  - hypervisor.hyperfleet.io
  resources:
  - hypervisorclusters/status
  - hypervisormachinetemplates/status
  - machineclaims/status
  - runnerpools/status
  verbs:
  - get
  - patch
  - update
