apiVersion: hypervisor.hyperfleet.io/v1alpha1
kind: HypervisorCluster
metadata:
  labels:
    app.kubernetes.io/name: hyperfleet-operator
    app.kubernetes.io/managed-by: kustomize
  name: hypervisorcluster-sample
spec:
  # TODO(user): Add fields here
